## Tannenspitzen-Gelee
__Quelle und weitere Informationen: https://github.com/OMerkel/recipes __

Zum https://omerkel.github.io/recipes/[__Rezepte-Index__ pass:[<font size="+3">&#x1F372;</font>]]

====
*TIPP* _Es können auch frische Fichtenspitzen verwendet werden. Im Frühjahr
werden nur die hellgrünen zarten Zweigspitzen gesammelt._
====

### Zutaten

[%interactive]
* [ ] etwa 200 bis 300 g frische Tannenspitzen
* [ ] 2 Zweige frischen Rosmarin oder Thymian
* [ ] 1,5 Liter Wasser
* [ ] Saft von 4 Zitronen
* [ ] 500 g 2:1 Gelierzucker

====
*TIPP* _Je nach gewünschter Festigkeit des Gelees kann auch 3:1 Gelierzucker verwendet werden._
====

### Zubereitung

[%interactive]
* [ ] Die gewaschenen Tannenspitzen und den Rosmarin/Thymian mit dem erhitztem Wasser einige Stunden (über Nacht) stehen lassen.
* [ ] Das Wasser abseihen, den Gelierzucker im Topf hinzugeben und unter ständigem Rühren zum Kochen bringen.
* [ ] Zitronen am Ende hinzugeben und den noch heißen Gelee in kochend heiß ausgespülte Einmach- oder Schraubgläser abfüllen und direkt verschließen.

====
*Hinweis* _Verwendet man Schraubgläser, so werden die dicht verschlossenen Gläser
direkt auf den Kopf gestellt. Nach kurzer Zeit (etwa 1 bis 2 Minuten) dann diese
wieder aufrecht stellen. Somit sollten die Gläser vakuumverschlossen sein._
====

====
*TIPP* _Werden ungespritzte Zitronen verwendet, so kann man mit einem
Zestenschneider die Schale in feinen Streifen geschnitten oder gerissen mit
in den Gelee geben, wodurch ein leicht bitterer Geschmack entsteht.
Insbesondere die zusätzlichen darin enthaltenen ätherischen Öle verleihen
dem Gelee zusätzliches Aroma._
====
